Logical\CloudCRP\mainBundle\Entity\cuentasTipo:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '50'
        letra:
            type: string
            length: '1'
        activo:
            type: boolean
    lifecycleCallbacks: {  }
