Logical\CloudCRP\mainBundle\Entity\partidas:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        codigo:
            type: string
            length: '50'
        fecha:
            type: date
        activo:
            type: boolean
        creado:
            type: datetime
            
        actualizado:
            type: datetime
    
    uniqueConstraints:
            codigo_idx:
                columns: [sucursal_id, codigo]
    
    manyToOne:
        sucursal:
            targetEntity: sucursales

    lifecycleCallbacks: {  }
