Logical\CloudCRP\mainBundle\Entity\sucursales:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '100'
        activo:
            type: boolean
    manyToOne:
        empresa:
            targetEntity: empresas
        creadoPor:
            targetEntity: User
    lifecycleCallbacks: {  }
