Logical\CloudCRP\mainBundle\Entity\transacciones:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        concepto1:
            type: string
            length: '255'
        concepto2:
            type: string
            length: '255'
        concepto3:
            type: string
            length: '255'
        monto:
            type: decimal
        tipo:
            type: boolean # 0 = debe | 1 = haber
        eliminado:
            type: boolean
    
    manyToOne:
        partida:
            targetEntity: partidas
        cuenta:
            targetEntity: cuentas

        creadoPor:
            targetEntity: User
    lifecycleCallbacks: {  }
